using System.Diagnostics;
using ModularityKit.Mutator.Abstractions;
using ModularityKit.Mutator.Abstractions.Engine;
using ModularityKit.Mutator.Abstractions.Metrics;

namespace ModularityKit.Mutator.Runtime.Internal.Execution;

/// <summary>
/// Carries mutation, state, and runtime metadata through the execution pipeline.
/// </summary>
/// <typeparam name="TState">The state type the mutation operates on.</typeparam>
/// <remarks>
/// This struct is created by <see cref="MutationEngine"/> before the pipeline
/// starts and flows through concurrency admission, policy evaluation, interception,
/// execution, and outcome processing. Using <c>readonly record struct</c>
/// avoids heap allocation per execution while preserving value semantics.
/// </remarks>
internal readonly record struct MutationExecutionContext<TState>
{
    /// <summary>
    /// The mutation instance being executed.
    /// </summary>
    /// <remarks>
    /// Provides access to the mutation's intent, context, <c>Apply</c>, <c>Validate</c>,
    /// and <c>Simulate</c> methods throughout the pipeline stages.
    /// </remarks>
    public IMutation<TState> Mutation { get; init; }

    /// <summary>
    /// The current state snapshot before mutation execution.
    /// </summary>
    /// <remarks>
    /// Passed to policy evaluation, validation, interception, and finally to
    /// <c>Apply</c> / <c>Simulate</c>. The executor produces the new state
    /// which replaces this value in the result.
    /// </remarks>
    public TState State { get; init; }

    /// <summary>
    /// Unique identifier for this execution, used in audit entries, history records,
    /// metrics scopes, and interceptor callbacks.
    /// </summary>
    /// <remarks>
    /// Generated by <see cref="MutationEngine"/> via <c>Interlocked.Increment</c>
    /// formatted as an eight digit hexadecimal string.
    /// </remarks>
    public string ExecutionId { get; init; }

    /// <summary>
    /// <c>Stopwatch.GetTimestamp</c> value captured at the start of execution, used
    /// to compute elapsed time via <c>Stopwatch.GetElapsedTime</c> without allocating
    /// <see cref="Stopwatch"/> instance.
    /// </summary>
    public long StartTimestamp { get; init; }

    /// <summary>
    /// Optional metrics scope for recording detailed execution diagnostics.
    /// </summary>
    /// <remarks>
    /// Allocated by <see cref="IMetricsCollector.BeginScope"/> only when
    /// <see cref="MutationEngineOptions.EnableDetailedMetrics"/> is <c>true</c>.
    /// When <c>null</c>, all metric-recording calls in the pipeline become no-ops
    /// and the result is returned without the <c>with</c> expression.
    /// </remarks>
    public IMetricsScope? MetricsScope { get; init; }

    /// <summary>
    /// Token used to observe cancellation requests throughout the execution pipeline.
    /// </summary>
    /// <remarks>
    /// Propagated to concurrency gate wait, policy evaluation, interceptor callbacks,
    /// executor, and outcome processor. The same token instance flows through the
    /// entire execution so that single cancellation source affects all stages.
    /// </remarks>
    public CancellationToken CancellationToken { get; init; }
}
